version: '3'

services:

    web:
        build:
            context: .
            dockerfile: ./docker/web/Dockerfile
        environment:
            DB_HOST: 'db'
        volumes:
            - .:/usr/src/trysanic
        ports:
            - "8000:8000"
        depends_on:
            - db
        
    db:
        image: "postgres:alpine"
        environment:
            POSTGRES_USER: "sanic" 
            POSTGRES_PASSWORD: "pass"
            POSTGRES_DB: "trysanic"

    worker1:
        build: 
            context: .
            dockerfile: ./docker/celery/Dockerfile
        volumes: 
            - .:/usr/src/trysanic
        environment:
            TELEGRAM_TOKEN: $TELEGRAM_TOKEN
        depends_on:
            - redis
            - rabbit

    worker2:
        build: 
            context: .
            dockerfile: ./docker/celery/Dockerfile
        depends_on:
            - redis
            - rabbit
        environment:
            TELEGRAM_TOKEN: $TELEGRAM_TOKEN
        volumes: 
            - .:/usr/src/trysanic
        command: celery -A trysanic worker -l info -Q high,default

    beat:
        build:
            context: .
            dockerfile: ./docker/celery/Dockerfile
        volumes: 
            - .:/usr/src/trysanic
        command: celery -A trysanic beat -l info

    redis:
        image: "redis:alpine"

    rabbit:
        image: "rabbitmq:alpine"
