version: '3'

services:

    web:
        build:
            context: .
            dockerfile: ./docker/web/Dockerfile
        environment:
            DB_HOST: 'db'
        volumes:
            - .:/usr/src/trysanic
        ports:
            - "8000:8000"
        depends_on:
            - db
        
    db:
        image: "postgres:alpine"
        environment:
            POSTGRES_USER: "sanic" 
            POSTGRES_PASSWORD: "pass"
            POSTGRES_DB: "trysanic"

    worker1:
        build: 
            context: .
            dockerfile: ./docker/celery_worker/Dockerfile
        environment:
            RESULT_BACKEND_HOST: 'redis'
            BROKER_HOST: 'rabbit'
        depends_on:
            - redis
            - rabbit
        volumes:
            - .:/usr/src/trysanic

    redis:
        image: "redis:alpine"

    rabbit:
        image: "rabbitmq:alpine"
